### ISSUE TITLE
Notes on the indices

### ISSUE THREAD

**Issue by liberostelios** [tudelft3d/3d-building-metrics#2]
# Overall

- Is equal volume sphere the best normalisation shape for the indices?
- How does grid density influence the result?
- How does precision of grid influence the result (`pyvista` issue).
- Quantify the time cost of every index.

# Individual

## Cohesion

Costly and time expensive.

## Proximity

Is based on distance of points from the "centre of mass", therefore how we compute the centre affects the result?

## Exchange

We compute the centre of mass from a grid, but that's time costly. We could find a better way?

## Depth

We assume that the formula of the distance of the boundary points to the centre of a sphere is `ρ - 3 / 4 * ρ = ρ / 4`.

**Comment by Athelena** [comment]
Traversal Index is VERY computationally expensive, we leave it for future work, perhaps we can test it towards the end but for now we skip it.

**Comment by Athelena** [comment]
Elongation can be a dynamic metric, depending on the direction of the bounding box the interpretation can be different. This can be seen in 2D as well but it's more profound in 3D.

**Comment by Athelena** [comment]
Elongation can be heavily skewed by vertical reference so can be computed for different vertical references. Also to check for things like chimneys. You can't adjust this in 2D.

**Comment by Athelena** [comment]
Equivalent rectangular index is very interesting. Compare horizontal vs. vertical complexity for different types of buildings.

**Comment by Athelena** [comment]
Play with voxel size? Or future work.

**Comment by Athelena** [comment]
3D indices are more computationally expensive and they are more fragile, i.e. susceptible to errors

**Comment by Athelena** [comment]
Maybe we don't trust the voxelisation process? Need to check.

**Comment by Athelena** [comment]
A sensitivity analysis to check how "trustworthy" we find specific indices. Play with the density.

**Comment by Athelena** [comment]
Use these metrics to identify non geometric errors?

**Comment by Athelena** [comment]
We need to experiment with different densities and see the comparisons between 2D and 3D.

**Comment by Athelena** [comment]
We move things to the origin, need to compare.
